-- 103038198
-- Coryn Tyrrell

-- TOUR (TOUR_NAME, DESCRIPTION)
-- PRIMARY KEY (TOUR_NAME)

-- CLIENT (CLIENT_ID, SURNAME, GIVEN_NAME, GENDER)
-- PRIMARY KEY (CLIENT_ID)

-- BOOKING (CLIENT_ID, DATE_BOOKED, PAYMENT)
-- PRIMARY KEY (CLIENT_ID)
-- FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT

-- EVENT (TOUR_NAME, CLIENT_ID, EVENT_YEAR, EVENT_MONTH, EVENT_DAY, FEE)
-- PRIMARY KEY (TOUR_NAME, CLIENT_ID, EVENT_YEAR, EVENT_MONTH, EVENT_DAY)
-- FOREIGN KEY (TOUR_NAME) REFERENCES TOUR
-- FOREIGN KEY (CLIENT_ID) REFERENCES BOOKING

