-- 103038198
-- Coryn Tyrrell

-- TOUR (TOUR_NAME, DESCRIPTION)
-- PRIMARY KEY (TOUR_NAME)

-- CLIENT (CLIENT_ID, SURNAME, GIVEN_NAME, GENDER)
-- PRIMARY KEY (CLIENT_ID)

-- EVENT (TOUR_NAME, EVENT_YEAR, EVENT_MONTH, EVENT_DAY, FEE)
-- PRIMARY KEY (TOUR_NAME, EVENT_YEAR, EVENT_MONTH, EVENT_DAY)
-- FOREIGN KEY (TOUR_NAME) REFERENCES TOUR

-- BOOKING (CLIENT_ID, TOUR_NAME, EVENT_YEAR, EVENT_MONTH, EVENT_DAY, DATE_BOOKED, PAYMENT)
-- PRIMARY KEY (CLIENT_ID, TOUR_NAME, EVENT_YEAR, EVENT_MONTH, EVENT_DAY)
-- FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT
-- FOREIGN KEY (TOUR_NAME, EVENT_YEAR, EVENT_MONTH, EVENT_DAY) REFERENCES EVENT


USE buildQuery;

CREATE TABLE TOUR (
    TOUR_NAME NVARCHAR(100),
    DESCRIPTION NVARCHAR(500),
    PRIMARY KEY (TOUR_NAME)
);

CREATE TABLE CLIENT (
    CLIENT_ID INT,
    SURNAME NVARCHAR(100) NOT NULL,
    GIVEN_NAME NVARCHAR(100) NOT NULL,
    GENDER NVARCHAR(1),
    CHECK (GENDER = 'M' OR GENDER = 'F' OR GENDER = 'I'),
    PRIMARY KEY (CLIENT_ID)
);

CREATE TABLE EVENT (
    TOUR_NAME NVARCHAR(100),
    EVENT_YEAR INT,
    CHECK (EVENT_YEAR <= 9999 AND EVENT_YEAR >= 1000),
    EVENT_MONTH NVARCHAR(3),
    CHECK (EVENT_MONTH = 'Jan' OR EVENT_MONTH = 'Feb' OR EVENT_MONTH = 'Mar' OR EVENT_MONTH = 'Apr' OR EVENT_MONTH = 'May' OR EVENT_MONTH = 'Jun' OR EVENT_MONTH = 'Jul' OR EVENT_MONTH = 'Aug' OR EVENT_MONTH = 'Sep' OR EVENT_MONTH = 'Oct' OR EVENT_MONTH = 'Nov' OR EVENT_MONTH = 'Dec'),
    EVENT_DAY INT,
    CHECK (EVENT_DAY >= 1 AND EVENT_DAY <= 31),
    FEE MONEY NOT NULL,
    CHECK (FEE > 0),
    PRIMARY KEY (TOUR_NAME, EVENT_YEAR, EVENT_MONTH, EVENT_DAY),
    FOREIGN KEY (TOUR_NAME) REFERENCES TOUR
);

CREATE TABLE BOOKING (
    CLIENT_ID INT,
    TOUR_NAME NVARCHAR(100),
    EVENT_YEAR INT,
    CHECK (EVENT_YEAR <= 9999 AND EVENT_YEAR >= 1000),
    EVENT_MONTH NVARCHAR(3),
    CHECK (EVENT_MONTH = 'Jan' OR EVENT_MONTH = 'Feb' OR EVENT_MONTH = 'Mar' OR EVENT_MONTH = 'Apr' OR EVENT_MONTH = 'May' OR EVENT_MONTH = 'Jun' OR EVENT_MONTH = 'Jul' OR EVENT_MONTH = 'Aug' OR EVENT_MONTH = 'Sep' OR EVENT_MONTH = 'Oct' OR EVENT_MONTH = 'Nov' OR EVENT_MONTH = 'Dec'),
    EVENT_DAY INT,
    CHECK (EVENT_DAY >= 1 AND EVENT_DAY <= 31),
    PAYMENT MONEY,
    CHECK (PAYMENT > 0),
    DATE_BOOKED DATE NOT NULL,
    PRIMARY KEY (CLIENT_ID, TOUR_NAME, EVENT_YEAR, EVENT_MONTH, EVENT_DAY),
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT,
    FOREIGN KEY (TOUR_NAME, EVENT_YEAR, EVENT_MONTH, EVENT_DAY) REFERENCES EVENT
);
GO


SELECT * FROM sys.tables;
GO